### ISSUE TITLE
Acceptance Tests fail on AWS dynamic build agent

### ISSUE THREAD

**Issue by kbaley** [Particular/NServiceBus.RavenDB#170]
Almost all tests fail with a variation on this error:

> Could not open database named: 13cd8e37-0fda-4491-8766-218d20ec4a84
> System.TimeoutException: The database 13cd8e37-0fda-4491-8766-218d20ec4a84 is currently being loaded, but after 5 seconds, this request has been aborted. Please try again later, database loading continues.

**Comment by kbaley** [comment]
Did some investigation on this but nothing conclusive yet. I created a static agent from the AMI and the tests would fail consistently. I thought it might be the version of Raven (currently 3.0.3660) but after leaving the agent for a day and running the tests again, they all pass.

**Comment by colin-higgins** [comment]
Is this still an issue with the latest database leak fixes?

**Comment by weralabaj** [comment]
@kbaley is that still a problem or can we close?

**Comment by kbaley** [comment]
@weralabaj I'm not sure if it's still happening. Someone in @Particular/ravendb-persistence-maintainers might know.

**Comment by DavidBoike** [comment]
Still a problem. Fighting it right now.

**Comment by DavidBoike** [comment]
It's a problem on builds and acceptance tests as well, as both require talking to the actual RavenDB server.

The solution is probably to change the 5 second database load limit to something more like 30 seconds. That's a server setting, so it would need to be updated on the build image.

For now, both ATs and Build configurations are configured with Agent Requirements > Explicit Requirements > `cloud.amazon.agent-name-prefix` **does not exist** so that they only run on the default agents, which is an imperfect solution for now.

**Comment by DavidBoike** [comment]
Tests seem to be succeeding on all agents now that the dynamic agents have local storage and not EBS storage, so there are not "Could not load database in 5 seconds" errors.
