### ISSUE TITLE
Need to remove Endpoint Version from calculation of ResourceManagerId

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus.RavenDB#178]
Going away in V6 and the calculation needs to remain stable starting with V5.

Related to #136

Currently the ResourceManagerId is a deterministic guid built off of the endpoint address and the endpoint version. This is used to facilitate side-by-side installations, so both simultaneous versions of an endpoint would have unique ids, otherwise they can throw DTC exceptions when running on the same system at the same time.

Two logically same endpoints could share transaction recovery storage, but if they ever do a recovery, any recovery file started under one resource manager id will be ignored by an endpoint operating with a new one. Thus it's imperative that this remain stable.

I think we need to learn under what conditions it can be proven that there is nothing left behind. If we could ensure that as long as an endpoint shuts down gracefully, no DTC recovery info is left behind, that gives us a lot more freedom.

//cc @andreasohlund 

## Reason for Prioritization

With transaction recovery changing to fix #136, the resource manager id must be dealt with as well. CoreV6 doesn't make EndpointVersion available, and the same formula needs to be used to ensure a smooth transition to V6.

**Comment by andreasohlund** [comment]
Since this would mean dataloss in v3 I'd say we need to patch this?

This would hit all users that increments their file version on each release which would be most users.

**Comment by andreasohlund** [comment]
I can't come up with any other way than forcing the users to supply a resource manager id if they are running in DTC mode?

**Comment by DavidBoike** [comment]
What did you consider and reject?

**Comment by andreasohlund** [comment]
If we generate it for them => we have to decide if we're going to loose data for people who run side by side or for people who upgrade their endpoints (right now we selected the latter). 

Since we can't find a way that works for all the only way forward seems to be to ask the users to provide it and educate them what they should put in depending on how they are running?

"If you do not plan to run side by side on the same machine you should pass in the endpointname"

"should you need to run side by side you need to XYZ"

**Comment by SimonCropp** [comment]
better to simply ask them to provide a full document store.

**Comment by andreasohlund** [comment]
>better to simply ask them to provide a full document store.

Interesting, I wonder if the fact that we used to internalize ravendb in the past has lead us astray since that forced us to not expose any ravendb types to the users. Now that we don't internalize anymore we could actually remove all the leaky abstractions and just have the users give us the document store to use.

@DavidBoike @Particular/persistence-maintainers thoughts?

**Comment by DavidBoike** [comment]
I think we're essentially forcing them to provide their own DocumentStore right now. Either that, or if they aren't, they're in real trouble and they don't know it. In any case, that seems to be where we're at right now and it's not really going too well.

I've got some ideas about this, and I'm talking to our Azure experts to make sure that case is covered as well. I think this is a solvable problem. I'm also looking into the Raven source to better understand the cases where we're safe, i.e. under what conditions we can assert that tx recovery storage is empty and every transaction is accounted for in the database. Then we can, for instance, have confidence that side-by-side works as long as the endpoint shuts down cleanly.

**Comment by DavidBoike** [comment]
Because including EndpointVersion in ResourceManagerId calculation is dangerous anyway (if you version on every release, without doing side-by-side deployment, the opportunity for data loss exists) we are removing it from the calculation for NServiceBus.RavenDB 4.0. ResourceManagerId will be a deterministic hash of `settings.LocalAddress()` alone.

Because of this, the upgrade guide will need to specify that care must be taken when upgrading, to ensure that endpoints shut down gracefully, and to check existing transaction recovery storage.
