### ISSUE TITLE
Can't specify a RavenDb session for TestableRavenStorageSession

### ISSUE THREAD

**Issue by jpv001** [Particular/NServiceBus.RavenDB#250]
TestableRavenStorageSession doesn't seem to work when specifying a IAsyncDocumentSession, regardless of whether or not the session is a real ravendb or an embedded ravendb, or a mocked session.

```
// Create an in memory store
var store = new EmbeddableDocumentStore { Configuration = { RunInMemory = true } };

// Or Connect to a real ravendb
//var store = new DocumentStore { Url = "http://localhost:8080", DefaultDatabase = "Test" };
store.Initialize();

Test.Saga<PolicySaga>().ConfigureHandlerContext(x =>
{
    x.SynchronizedStorageSession = new TestableRavenStorageSession(store.OpenAsyncSession());
})
.WhenHandling<IAccountInvoiceUpdated>(invoice =>
{
    invoice.AccountInvoiceId = invoiceId;
})
.ExpectTimeoutToBeSetAt<PolicyDueTimeout>((x, y) => x.DueDate == y.Date);
```

The line in the saga that fails is:
``` 
var session = context.SynchronizedStorageSession.RavenSession();
```
The exception is always: 
It was not possible to retrieve a RavenDB session.

**Comment by DavidBoike** [comment]
@jpv001 Thanks for the report! We'll make sure to fix this in the next beta release.

This is because:

* `RavenDBSynchronizedStorageSession` inherits `CompletableSynchronizedStorageSession`
* `TestableRavenStorageSession` inherits `SynchronizedStorageSession`
* `RavenSession()` extension method attempts to cast synchronized session to `RavenDBSynchronizedStorageSession` which fails when it's a testable session.

Options:

* The reason [testable session](https://github.com/Particular/NServiceBus.RavenDB/blob/release-4.0.0/src/NServiceBus.RavenDB/Testing/TestableRavenStorageSession.cs) doesn't inherit [RavenDBSynchronizedStorageSession](https://github.com/Particular/NServiceBus.RavenDB/blob/release-4.0.0/src/NServiceBus.RavenDB/SessionManagement/RavenDBSynchronizedStorageSession.cs) is because it would be a public inheriting an internal class. We could make both public.
* Introduce an interface

@Particular/ravendb-persistence-maintainers thoughts?

**Comment by mauroservienti** [comment]
`CompletableSynchronizedStorageSession` is already an interface, public provided by Core. I don't see any issue in either making `RavenDBSynchronizedStorageSession` a public class or introducing a `IRavenDBSynchronizedStorageSession` public interface that inherits from `CompletableSynchronizedStorageSession` and make the testable session implement it and change the `RavenSession` extension depend on it.

On the simpler side of things, can't we simply make the `RavenSession` extension aware that there can be 2 implementations? check for which one we are using and cast to that? yes...I'm suggesting an awful `if` statement that would allow us to implement a quick and transparent fix, without the need of making any type public or without the need of introducing a public interface for this specific purpose, especially knowing that we cannot get easily rid of them if we change our mind going further, being a breaking change.

**Comment by DavidBoike** [comment]
Fixed in #258 and will be in the next beta. There's a new beta of the Core coming very soon, so we will wait until we have incorporated those changes before releasing the new beta.

**Comment by adamralph** [comment]
Was this a v6-only bug?

**Comment by DavidBoike** [comment]
@adamralph:

> Was this a v6-only bug?

Correct
