### ISSUE TITLE
Using the nested / inner class name only for saga data in the DocumentStore convention can cause confusion

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.RavenDB#278]
Basically the same issue as https://github.com/Particular/NServiceBus.Persistence.AzureStorage/issues/100 but for RavenDB.

Imagine having the following sagas:

``` c#
public class MyFirstCoolSaga
{
    public class Data : ContainSagaData
    {
        public long Id { get; set; }
    }
}

public class MySecondEvenCoolerSaga
{
    public class Data : ContainSagaData
    {
        public long Id { get; set; }
    }
}
```

Both saga data classes will now store their data in a `Data` document. This can result in conflicts.

Comparing this to NHibernate, NHibernate uses the name from the parent/outer class. The sagas seen in the following image use the same construction as the mentioned snippet above.

# Proposal

1. Use the same behavior as NHibernate, use the outer class name
2. Use the outer class name and the nested class name
3. Use the full type name (namespace + outer + nested names)

# References

- This issue was found while implementing https://github.com/Particular/EndToEnd/issues/198

**Comment by mauroservienti** [comment]
Thanks @ramonsmits. We could do different things to address the issue, the thing I don't like is that whatever we do we need to deal with `DocumentStore` conventions with the risk of screwing up user settings.

@ramonsmits 

> This can result in issues.

Can you detail issues you think can arise? Because the same situation can happen if users have 2 sagas with the same SagaData name into 2 different namespaces.

Would be documenting this, potential issues and suggested workaround enough?

@Particular/ravendb-persistence-maintainers thought?

**Comment by DavidBoike** [comment]
We absolutely can't change naming conventions at this stage. I think the only thing we can do is document to "don't do that".

**Comment by ramonsmits** [comment]
The issue here is that different saga instances can match. I use this model very often to make the data a nested class and accidentally I bumped into this issue.

If this is a RavenDB default then I think we shouldn't modify this behavior but if it is us the

What about a warning/error? If we detect that the saga data class is a nested type that we mention that the user must be aware of default ravendb naming conventions?

**Comment by mauroservienti** [comment]
it's RavenDB default, by default they can't match unless you are using the same GUID value for the ID of 2 different Sagas. In you sample the `Id` property must be a GUID AFAIK.

Though, there is an interesting scenario that can screw up things for the user:

```c#
public class MyFirstCoolSaga
{
    public class Data : ContainSagaData
    {
        [Unique]
        public String OrderId { get; set; }
    }
}

public class MySecondEvenCoolerSata
{
    public class Data : ContainSagaData
    {
        [Unique]
        public String OrderId { get; set; }
    }
}
```

Now we have 2 different Sagas that can legitimately be linked to the same Order (via the `OrderId` property), due to the way we generate the `Unique Document` Id I suspect that we end up with 1 unique document pointing to the saga created last.

@Particular/ravendb-persistence-maintainers thoughts?

**Comment by mauroservienti** [comment]
@Particular/ravendb-persistence-maintainers the above can lead to data loss, what should we do?

**Comment by DavidBoike** [comment]
Possible approach: Cause the persister to throw if the second saga is trying to overwrite the unique pointer document.

Not sure exactly what the behavior is currently.

Changing the document id strategy for sagas or pointer documents is not something we want to consider at this point as it would be very risky and probably end up biting us eventually.

**Comment by ramonsmits** [comment]
Additional info as visible in RavenDB Studio:

![image](https://cloud.githubusercontent.com/assets/152998/18787811/b775d47c-81a4-11e6-9d55-a45f4b70c5a6.png)

Because we generate our own ID's this is not causing serious issues visualization in RavenDB.

Instead of seeing 2 documents of type *SagaCongestionDatas* I expected just of that type and one of type *SagaCongestionRunner-SagaCongestionDatas*.

**Comment by weralabaj** [comment]
@mauroservienti @DavidBoike would be great if you could double check, but I think we're on the safe side. When we look for sagas to correlate (when a new message comes in) we don't query saga datas directly, but saga unique identities. Those latter have outer class (and namespace) inlcuded in the name.

Seems we're safe?

**Comment by ramonsmits** [comment]
Even though we are safe could can we maybe influence the document name? Maybe it is possible to configure a generic naming convention?

**Comment by weralabaj** [comment]
>  influence the document name

@ramonsmits changing the document name would mean we need to migrate the old documents, which is (honestly) simply scary :P that's why we're trying to avoid that as a plague.

I agree that it's not the optimal solution, hard to understand, poor visualization, but I think unless that's a critical bug (information loss scenario) IMO it's just too risky change and it's more reasonable to come to terms with the technical debt we have.

At least that's the impression I got from our previous conversations with @mauroservienti and @DavidBoike. Please, correct if I misunderstood something!

**Comment by ramonsmits** [comment]
@weralabaj I'm not suggesting to put that in the code and override current behavior. It could be just a opt-in setting or maybe just a snippet in the RavenDB doco.

**Comment by DavidBoike** [comment]
This is a longstanding issue. I don't think it merits consideration for 4.0.0 RTM, so I'm going to move it to the 4.0.1 milestone.

**Comment by lailabougria** [comment]
@ramonsmits We looked into this, and in v6 Raven introduced a [new storage format for saga data](https://docs.particular.net/persistence/upgrades/ravendb-5to6), wrapping the saga data into another document. That now has a unique identifier called IdentityDocId. The way [this one is determined](https://github.com/Particular/NServiceBus.RavenDB/blob/65f259413452ea7674dbd081745f43fcaae67e46/src/NServiceBus.RavenDB/SagaPersister/SagaUniqueIdentity.cs#L14) is by using the type's full name, there's a character replacement in place to replace + by -. Therefore, we think this is now a non-issue.
