### ISSUE TITLE
Assumption that Queue == EndpointName not always valid

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus.RavenDB#280]
From @janovesk:

> https://github.com/Particular/NServiceBus.RavenDB/blob/23b8caed78ccd43c4db8ddb7d79b424642a79f76/src/NServiceBus.RavenDB/Internal/LegacyAddress.cs#L25

> When we convert from v1 subscriptions to v2 subscriptions, that code makes an assumption that it can set the logical endpoint name to the queuename from the phsyical address stored in v1. This is actually not quite safe. Probably correct in 99% of the cases, but it is perfectly legal to have A@machine1 and A@machine2 subscribed WITHOUT them being physical deployments of the same logical endpoint.

However, there may not be anything we can do as there is no additional information at conversion time to consider.

**Comment by mauroservienti** [comment]
Should we be able in Core V6 to "query" the routing config to gather the info we're missing at conversion time?

**Comment by weralabaj** [comment]
How subscription looks in V5 (for Pub-Sub sample from docs)

<img width="433" alt="v5" src="https://cloud.githubusercontent.com/assets/7335079/18832163/16ac1324-83ea-11e6-82d0-fff413289f99.PNG">

in V6

<img width="575" alt="v6" src="https://cloud.githubusercontent.com/assets/7335079/18832169/1dcb6dc6-83ea-11e6-87de-ae554fd114f1.PNG">

So in V5 we simply don't have information on the subscription level to differentiate between queue name and endpoint name. 

Now, my understanding is that after we upgrade the endpoint something changes, then we'll receive the missing information from core in the subscription message (based on the comment from Tim here https://github.com/Particular/NServiceBus.RavenDB/issues/281#issuecomment-247623304).

Now since we operate on physical addresses and don't take endpoint name when returning descriptions (after fixing the bug), does it matter that we have occasionally incorrect information?

If so, what's the exact scenario?

ping @janovesk

**Comment by janovesk** [comment]
It's very edge case, but there is a small loophole here. 

Let's say you have three v5 endpoints A@machine1, B@machine2 and B@machine3. B@machine2 and B@machine3 are not logical equivalent. They just happen to share B as their queue name. They both subscribe to A. Subscription store for A contains: (B@machine2), (B@machine3). Publish will send to BOTH 
(B@machine2) and (B@machine3).

Now you upgrade A to V6. The subscription store becomes:  (B@machine2, B), (B@machine3, B). (Where the B at the end is the endpoint name). At publish it will group by endpoint name, pick one from each group and publishes to it ONLY. The other endpoints in the same group will not get the message.  Potential message loss here.

As soon as you upgrade B@machine2 and/or B@machine3 you will get the actual endpoint name in the subscription message. That will overwrite(given https://github.com/Particular/NServiceBus.RavenDB/pull/284) the "deduced" logical name from the conversion so that the subscription store in A becomes: (B@machine2, logical-name-for-this), (B@machine3, logical-name-for-that). These will group into two groups at publish time, resulting in the two message that need to be published. So it will self-fix as soon as you upgrade your subscribers, but that might be some time off.

Not many people will have B@machine2 and B@machine3 without them actually being instances of the same endpoint, but it is fully allowed and supported in pre-v6. 

Ping @weralabaj

**Comment by weralabaj** [comment]
Then solution would be when converting, instead of assuming queue name == endpoint name, to insert null instead of endpoint name?

That seems to make the most sense.

**Comment by janovesk** [comment]
Indeed. That is what NHibernate subscription store does as well.

**Comment by weralabaj** [comment]
👍

**Comment by weralabaj** [comment]
Resolved in https://github.com/Particular/NServiceBus.RavenDB/pull/284.
