### ISSUE TITLE
Calling `TimeToWaitBeforeTriggeringCriticalErrorOnTimeoutOutages` doesn't work

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.RavenDB#312]
Calling `endpointConfiguration.TimeToWaitBeforeTriggeringCriticalErrorOnTimeoutOutages(..)` as documented at the following location does not seem to work and seems to be not implemented.

- https://docs.particular.net/nservicebus/messaging/timeout-manager?#handling-of-persistence-errors

**Comment by mauroservienti** [comment]
@ramonsmits I investigated a little bit and it seems that this behavior is not controlled in any way by downstream persistence packages. It is entirely under Core control. I'll investigate more because the only thing I found is a difference in the acceptance test suite that comes with Core 6.0.0 and the one that comes with Core 6.1.2

Assigning to myself.

**Comment by ramonsmits** [comment]
@mauroservienti Did you make any progress on this issue?

**Comment by mauroservienti** [comment]
As said it's not a downstream concern. It's all controlled by Core.

**Comment by mauroservienti** [comment]
We don't have any code to deal with that. Persistence simply throws in case of issues with the storage.

**Comment by ramonsmits** [comment]
You are right @mauroservienti , it seems to be cause do to current behavior of the timeout manager. I've raised an issue about it the NServiceBus repo and I'll close this one:

- https://github.com/Particular/NServiceBus/issues/4833
