### ISSUE TITLE
Start adding persistence assembly version to documents stored in RavenDB

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.RavenDB#320]
In order to simplify the migration process of NServiceBus related documents stored in RavenDB we need to add to every document a version metadata to alleviate the conversion process.

**Comment by danielmarbach** [comment]
We decided to introduce a data schema version instead that we persist. We set the current data schema to `1.0.0`. Should we ever change the schema of Outbox, Sagas, Subscriptions or Timeouts we can update the versions independently. The reason is we don't feel the persister version is really meaningful. For example to support NServiceBus v8 we would need a major version of the persister but potentially not touch the schema version. Therefore the schema version should not change just because the persister version change.

**Comment by adamralph** [comment]
FTR schema versioning introduced in https://github.com/Particular/NServiceBus.RavenDB/pull/504
