### ISSUE TITLE
Support for NServiceBus 7 on dotnet core

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.RavenDB#367]
It is impossible to use RavenDB with NServiceBus 7 on dotnet core. RavenDB with NServiceBus 7 only works with .net framework.

**Comment by ChrisEvansUM** [comment]
Hi ramonsmits,

There's a branch in the repo targeting dotnet standard, is that no longer being pursued?  Also, can you let me know why this is impossible?  RavenDb are updating their client and server so both can be run on dotnet core 2 - just wondering if there's something we've missed?  As far as I can see as long as we're not using DTC, theoretically it should work (with some work obviously).

Kind regards,

Chris Evans

**Comment by mauroservienti** [comment]
Hi Chris,

we're not yet there. We will support .NET Standard with RavenDB 4 that is around the corner.

There is more work involved in supporting .NET Standard with RavenDB 3.5. Given that is something we can do in a minor we'll reevaluate .NET Standard support for RavenDB 3.5 as we release the next major that targets NServiceBus V7 (with full framework only support).

The main blocker at the moment is that our test infrastructure relies on 3.5 embedded server that is not supported on .NET Core, preventing us to test persistence with .NET Core on Windows and especially on Linux.

**Comment by DavidBoike** [comment]
@rvhelden The RavenDB persistence we'll ship with NServiceBus 7 for .NET Core (NServiceBus.RavenDB 5.0) will use RavenDB 3.5 (and support .NET Core) so that customers don't have to upgrade RavenDB to upgrade NServiceBus.

By the way that's already in RC with a go-live license you can use in production.

After that's fully released we'll start to consider RavenDB 4.0 support.

**Comment by DavidBoike** [comment]
@zeko77 I know you're asking specifically about RavenDB 4.0, but this issue is actually about supporting RavenDB with NServiceBus 7 on .NET Core, which is complete. So in the interests of clarity, I hope you'll forgive me for closing this issue, and replacing it with [this one instead](https://github.com/Particular/NServiceBus.RavenDB/issues/412) where I'll answer your question as best as I can today.
