### ISSUE TITLE
TCP port exhaustion

### ISSUE THREAD

**Issue by Bishbulb** [Particular/NServiceBus.RavenDB#437]
We are observing that TCP connections to RavenDB are being leaked at a rate of about one per minute by each of our NServiceBus handlers. This can be observed by starting up the handler, going to Task Manager to get the process ID for the handler, then opening Powershell and running `netstat -ano | findstr <YOUR_PROCESS_ID>`. This will print output similar to:
>   TCP    127.0.0.1:59424        127.0.0.1:8090         ESTABLISHED     9204
  TCP    127.0.0.1:59429        127.0.0.1:8090         ESTABLISHED     9204
  TCP    127.0.0.1:59430        127.0.0.1:8090         ESTABLISHED     9204
  TCP    127.0.0.1:59483        127.0.0.1:8090         ESTABLISHED     9204
  TCP    127.0.0.1:59484        127.0.0.1:8090         ESTABLISHED     9204
  TCP    [::1]:59427            [::1]:5672             ESTABLISHED     9204
  TCP    [::1]:59428            [::1]:5672             ESTABLISHED     9204

If you run the command again in a few minutes, you will see that there are additional TCP connections to RavenDB (port 8090 in the above example) that are all in a status of ESTABLISHED.

In our application we have over 25 different NServiceBus handlers each leaking TCP connections. I believe that Windows defaults to allowing 5000 TCP connections, so we are eating through these about once every 200 minutes (~3 hours), with the only workaround being to regularly stop and restart the NServiceBus handlers.

Here are the package versions we're using:

- RavenDB.Client 4.2.2
- NServiceBus.RavenDB 6.0.0
- NServiceBus 7.1.10
- NServiceBus.RabbitMQ 5.1.2
- NServiceBus.StructureMap 7.0.0
- NServiceBus.Newtonsoft.Json 2.2.0
- NServiceBus.Heartbeat 3.0.1

If there's any additional information I can provide, please let me know.

**Comment by Bishbulb** [comment]
I have created a repo with a sample application that reproduces the issue:
https://github.com/Bishbulb/NServiceBus.RavenDB4.TCPIssue

Note that this includes some custom infrastructure that we use for running our NServiceBus hosts, so it isn't necessarily a "minimal" reproduction.  You can look at the `ConfigureEndpoint` class and see how we are creating our own `DocumentStore` to pass in to the NServiceBus infrastructure. I doubt that this would be related to the TCP connection leaks, but its worth highlighting.

**Comment by DavidBoike** [comment]
@Bishbulb Since the NServiceBus persistence code operates much higher than the TCP level, I'm assuming that in order for this to be an NServiceBus issue (rather than a RavenDB issue), there would have to be some IDocumentSession or something left undisposed, right?

I also assume that since you are using Rabbit there's obviously no subscriptions, and due to the version of the transport you're using, you're using native Rabbit timeouts as well, which leaves us with just Outbox and Sagas, correct? But since your repro doesn't include any sagas either, we're really only dealing with the outbox. Correct?

So there's really not a whole lot of places a session could get created.

Here's the [OpenAsyncSessionBehavior](https://github.com/Particular/NServiceBus.RavenDB/blob/master/src/NServiceBus.RavenDB/SessionManagement/OpenAsyncSessionBehavior.cs). When you don't have Outbox (the else case) you can see the session is wrapped in a using. The Outbox case is above, the session was already created earlier in the pipeline and the behavior turns into a no-op.

In the [OutboxPersister](https://github.com/Particular/NServiceBus.RavenDB/blob/master/src/NServiceBus.RavenDB/Outbox/OutboxPersister.cs), every usage of `GetSession` is within a using block except [BeginTransaction](https://github.com/Particular/NServiceBus.RavenDB/blob/master/src/NServiceBus.RavenDB/Outbox/OutboxPersister.cs#L54-L63), where it's created and added to the context and the "transaction" object is returned to NServiceBus. Here's the [transaction class](https://github.com/Particular/NServiceBus.RavenDB/blob/master/src/NServiceBus.RavenDB/Outbox/RavenDBOutboxTransaction.cs) that disposes the session when it is disposed itself. But in the Core, that BeginTransaction API is called from the [TransportReceiveToPhysicalMessageProcessingConnector](https://github.com/Particular/NServiceBus/blob/7.1.10/src/NServiceBus.Core/Pipeline/Incoming/TransportReceiveToPhysicalMessageProcessingConnector.cs#L34-L44) and within a using.

The only Outbox operation left is the [OutboxRecordsCleaner](https://github.com/Particular/NServiceBus.RavenDB/blob/master/src/NServiceBus.RavenDB/Outbox/OutboxRecordsCleaner.cs), which uses a DeleteByQueryOperation directly, but those aren't disposable.

Am I missing anything or have any assumptions wrong?

**Comment by Bishbulb** [comment]
@DavidBoike I agree that the issue must be something being left undisposed. Since we can reproduce this by just starting the handler and doing nothing further, it points to something periodic (ie. outbox) compared to something that only occurs during message processing (ie. sagas).

I just tried commenting out `endpointConfiguration.EnableOutbox()`, and the problem seems to go away. That suggests that somehow, the issue is related to the `OutboxRecordsCleaner`, since that is the only task that runs periodically in the handler when no messages are being processed.

I'm going to dig into this further to see what else I can find.

**Comment by Bishbulb** [comment]
@DavidBoike The problem is definitely in the OutboxRecordsCleaner. If I enable the outbox and comment out the details of the `RemoveEntriesOlderThan` method, I don't see any TCP connections leaking. As soon as I re-enable that code, I get the connections leaking. 

Going to continue to digging to see what could be wrong with how the RavenDB API is being used there, as I can't see what would be wrong at first glance.

**Comment by Bishbulb** [comment]
@DavidBoike OK. The TCP connection is definitely leaking as a result of calling `await operation.WaitForCompletionAsync()`, which points the finger at RavenDB being the culprit. 

I'm going to try and come up with an isolated repro and then I'll post it to the RavenDB team for their investigation.

**Comment by Bishbulb** [comment]
@DavidBoike I've logged an issue [here](https://issues.hibernatingrhinos.com/issue/RavenDB-13884)

**Comment by DavidBoike** [comment]
Thanks @Bishbulb, I've followed the YouTrack issue. Since we've (at least it seems) exonerated NServiceBus, I'm going to close this issue until we discover otherwise.
