### ISSUE TITLE
Resolve user provided IDocumentStore during endpoint startup

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.RavenDB#444]
As [reported by a user on the mailing](https://discuss.particular.net/t/nservicebus-ravendb-delay-init-until-endpoint-startup/1450/3) the [persister resolves the `Func` passed to `SetDefaultDocumentStore` when the features are setup](https://github.com/Particular/NServiceBus.RavenDB/pull/443).

This prevents users using `IServiceCollection` or on immutable containers such as SimpleInjector and Autofac to resolve the document store from their container.

There is no known workaround at this stage.

**Comment by andreasohlund** [comment]
As an aside, we also do indexing at this time which arguably also isn't ok since I would expect that to happen during startup?

**Comment by mauroservienti** [comment]
I think I see what the problem is, I guess we can replace all `IDocumentStore` dependencies with something like `Lazy<IDocumentStore>` or pass in the `Func<>` and let components resolve the document store only when it's needed.

The only issue are indexes, the store is needed to create indexes and those need to be created/updated when the endpoint starts up.

**Comment by andreasohlund** [comment]
I think we can move the indexing to a `FeatureStartupTask`?

**Comment by andreasohlund** [comment]
I've raised a follow up issue that is an extension of this issue

https://github.com/Particular/NServiceBus.RavenDB/issues/445
