### ISSUE TITLE
Use Raven native id assignment to improve saga inserts perf

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.RavenDB#45]
Raised by @johnsimons
Migrated from by https://github.com/Particular/NServiceBus/issues/1973

### Description

As part of fine tuning SC to handle a high volume of messages we have identified a bottleneck on our ravenDB saga persistence.

The issue is that **we** auto gen our own docs ids and those ids are not the ideal for Raven inserts, which causes the insertions to get slower as the data grows.

So the solution is to let Raven auto gen its own ids using HiLo.

### Implementation

Looking at the current code base, one way I see us moving forward with this is to have a in-memory mapping of `NSB id <-> Raven id`.
So when we instantiate `RavenSagaPersister` we perform a query to initialize this in-memory mapping and then we keep it up to date on all inserts/deletes
This would be actually quite simple to spike?

@andreasohlund thoughts?

**Comment by SimonCropp** [comment]
@johnsimons do u still think this is worth investing time in?

**Comment by johnsimons** [comment]
@SimonCropp,
I think our current saga impl when running with raven has quite a low throughput, don't you think we should investigate and find out if there is anything we can tweak to improve it?

**Comment by andreasohlund** [comment]
The issue is with perf (my hunch at least is)

1. We use combguids which is terrible for the insert perf since it will split the b-tree raven uses
    - I've confirmed this with Oren
2. We are forces to insert 2 docs for each saga
    - 1 For the saga data it self
    - 1 to mimic unique key constraints

Me and @jbogard talked about this a while back and the result was this proposal:

https://github.com/Particular/NServiceBus/issues/2445

which depends on:

https://github.com/Particular/NServiceBus/issues/2444

While we can try to go with a native id, is the time better spent making progress on the issues above?

**Comment by DavidBoike** [comment]
The only way to do this would be to add another pointer document for the sagaId, which would be an additional insert and still rely on b-tree splitting guids. This can't be solved from the NSB.Raven side.
