### ISSUE TITLE
Use document expiration by default for outbox deduplication data clean up

### ISSUE THREAD

**Issue by adamralph** [Particular/NServiceBus.RavenDB#518]
In NServiceBus.RavenDB 6.3 we introduced [an option to use document expiration to clean up outbox deduplication data](https://github.com/Particular/NServiceBus.RavenDB/issues/406).

In a future major version, we should switch to this as the default method, and consider deprecating the previous clean up method.

**Comment by mauroservienti** [comment]
> In a future major version, we should switch to this as the default method, and consider deprecating the previous clean up method.

@kbaley and I had a look at this and we don't see a good reason to deprecate the current functionality and make the expiration bundle the default. The main reason is that the expiration bundle configuration is a RavenDB server-wide global configuration which means that if users are already using the feature for their own business data and the expiration cleanup process is set to run monthly the outbox will use the same settings which might be far from ideal.

We're inclined to leave, for now, the situation as is. @lailabougria thoughts?

**Comment by mauroservienti** [comment]
For our future selves, we could implement this by:

- in a minor
  - emit a warning in the logs if the `FrequencyToRunDeduplicationDataCleanup` is not set and it's using the default value of 1 minute.
  - If there is a setting set by users, even if set to the internal default, the warning is not emitted, which means users want to use the internal clean process or they want to intentionally disable it
  - We cannot deprecate the `SetFrequencyToRunDeduplicationDataCleanup` extension method because it's needed anyway to use the builtin cleaner if the expiration bundle is not an option

- in a subsequent major:
  - change the `FrequencyToRunDeduplicationDataCleanup` to `Timeout.InfiniteTimeSpan` which disables the internal clean process
  - remove the warning emitted
