### ISSUE TITLE
RavenDBSynchronizedStorage doesn't make RavenDB session available for behaviors

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus.RavenDB#532]
In [RavenDBSynchronizedStorage](https://github.com/Particular/NServiceBus.RavenDB/blob/master/src/NServiceBus.RavenDB/Internal/RavenDBSynchronizedStorage.cs#L14-L21), an `IAsyncSession` and the `SynchronizedStorageSession` that enables it to be shared with handlers is created, but not added to the `ContextBag`. That means that even when using the Outbox (meaning the sessions should be available from very early in the pipeline due to the dedupe check) you can't get at the session until the InvokeHandlers stage, unless you're willing to use reflection.

This has been implemented in https://github.com/Particular/NServiceBus.RavenDB/pull/619 and https://github.com/Particular/NServiceBus.RavenDB/pull/644.

---

In the [LoadHandlersConnector](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Pipeline/Incoming/LoadHandlersConnector.cs#L28), the `storageSession` is finally extracted from the `outboxTransaction`. This can technically be done earlier, but because [RavenDBOutboxTransaction](https://github.com/Particular/NServiceBus.RavenDB/blob/master/src/NServiceBus.RavenDB/Outbox/RavenDBOutboxTransaction.cs) is internal, you have to use reflection to grab the `IAsyncDocumentSession` out of that.

The upshot is that it's quite difficult to use the Raven session in a behavior in the Physical/Logical phases of the incoming pipeline.

This could be fixed by [adding `session` and `synchronizedStorageSession` to the context directly after they're created](https://github.com/Particular/NServiceBus.RavenDB/blob/master/src/NServiceBus.RavenDB/Internal/RavenDBSynchronizedStorage.cs#L17-L18).

**Comment by Bishbulb** [comment]
In our scenario, the reason we wanted access to the Raven session earlier in the pipeline is actually so that we can setup our IoC container to inject the IAsyncDocumentSession into our message handlers. We like that the session unit of work is managed by NServiceBus (via the Outbox), but we still want to be able to pull that same session and inject it into other components using traditional IoC. If we wait to the LoadHandlersConnector behavior, the message handlers have already been instantiated and it is too late to modify the IoC container. 

I hope this helps to explain why we were looking for access to RavenDB earlier in the pipeline.

**Comment by kbaley** [comment]
We've started looking at this in our current maintenance release and believe we can do this using a similar method as the SQL Persister

/cc @Bishbulb

**Comment by mauroservienti** [comment]
this is done in https://github.com/Particular/NServiceBus.RavenDB/pull/619
