### ISSUE TITLE
Make saga pessimistic lease lock the default behavior

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.RavenDB#538]
In NServiceBus.RavenDB 7 the default behavior of the saga persister will be to use pessimistic locks when accessing saga data instances. This has been implemented in https://github.com/Particular/NServiceBus.RavenDB/pull/611.

NServiceBus.RavenDB 6.5 introduces a pessimistic lock option to allow users to prepare their environment to switch. This has been implemented in https://github.com/Particular/NServiceBus.RavenDB/pull/613

**Comment by kbaley** [comment]
We're working on this for the current RavenDB maintenance release. Since we're changing the API, this is a breaking change. We'll add it to `master` but likely won't release it in anticipation of further changes to accommodate NSB v8.

We're also adding `EnableOptimisticConcurrency` to the current release and marking `EnablePessimisticConcurrency` as obsolete to help people prepare.

**Comment by mauroservienti** [comment]
This is done in https://github.com/Particular/NServiceBus.RavenDB/pull/611
