### ISSUE TITLE
Ensure compatibility between the old and new raven API

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.RavenDB#6]
So we have people who are persisting things using the raven parts in the core. now we are externalising those parts into the assembly produced by this repository

We need to ensure that people can move over to the new approach in the simplest possible manner. so ideally with no migration or if there is migration involved document it well or perhaps write a tool to perform this migration.

- [ ] Produce some integration tests that verify the process
- [ ] automate as much as possible if it is not seamless 
- [ ] document any manual steps people need to take

**Comment by danielmarbach** [comment]
@SimonCropp @johnsimons claimed this should be done. What is the state? Can we close?

**Comment by SimonCropp** [comment]
@johnsimons if this is done where is it?

**Comment by johnsimons** [comment]
@SimonCropp this was done as part of releasing the first version of this package, we were able to complete this without any migration required by the users.
The change was done in https://github.com/Particular/NServiceBus.RavenDB/commit/432211a9cab597af2186208e4bc0ec68f18a53c1

Unfortunately, we were not able to automate the testing of such transition because our acceptance test framework currently does not allow us to start/stop endpoints in a deterministic way.

A possible option here is to use our "backwards compatibility tests" to execute such scenario, what do you think?

**Comment by mauroservienti** [comment]
As stated this seems to be done, closing. Feel free to re-open if I'm missing something.
