### ISSUE TITLE
Honor the unique properties in the saga metamodel

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.RavenDB#64]
The new metamodel in core v6 contains the properties that are unique. The persister should honor this.

This is how the InMemory persister is currently doing it

https://github.com/Particular/NServiceBus/issues/346

**Comment by andreasohlund** [comment]
Also note that the current Raven saga persister doesn't allow more than one unique property per saga while the core metamodel allows for this. So we need to validate and throw here if that is the case

**Comment by andreasohlund** [comment]
Think this is an easy fix. Should we consider including this in 3.0 cc @danielmarbach ?

**Comment by danielmarbach** [comment]
This would mean we couple RavenDB 3.0 support to new V6 of core release?

**Comment by andreasohlund** [comment]
Yea, that's to early. Lets defer for now and do it when core v6 is ready.

Especially if we're contemplate changing the ISagaPersister interface

**Comment by synhershko** [comment]
+1 @danielmarbach  - its too early. Future versions of NSB.RavenDB targeting NSB v6 should be made to handle this.

**Comment by danielmarbach** [comment]
I think we have a wording issue here. The core defines those properties as correlated properties and not unique :)

**Comment by SimonCropp** [comment]
@andreasohlund @danielmarbach 

a few things are going to make this complex

currently:

 * we currently support multiple correlation properties
 * we dont force them to be unique
 * so we can have existing data that has multiple sagas with the same correlation id

So assuming we change ravendb to support multiple unique (ie every correlation property) what do we do with existing data? Do we need to provide a migration patching tool?

Am I missing something and this is actually trivial to solve?

**Comment by danielmarbach** [comment]
@davidboike and I agreed to habe a metadata check at startup which throws
when you have multiple unique for the first round and then think about
whether we want to support multiple unique. Sorry doesn't answer your
question but buys me time to reflect ;)

-- 
*#NSBcon 2015 • The "All About NServiceBus" conference is back *
*• Learn more <http://go.particular.net/l/27442/2015-08-21/5d4wzp> →*

**Comment by DavidBoike** [comment]
With NHibernate multiple unique properties is no sweat. You just add another unique constraint.

With RavenDB it's just a bad idea. Additional unique constraints would force additional pointer documents, which means more documents that must be dealt with on every single saga modification, which would not be good for perf. Also I think we would run into the limitations of what you can do with a Raven Include<TDocument>(), meaning more round-trips to the database just as a matter of course.

Current Raven implementation stores the DocId of the pointer document in the saga as a single property. To support multiple properties that would have to change to a collection, and then migration becomes a huge issue. 

Beyond all this, I have yet to hear a really solid use case where multiple mapped (unique) properties in a saga is really necessary or can't be worked around.

Given a lack of solid use case, plus the large perf and migration problems, I don't think it's useful to go to a bunch of trouble to chase what-ifs. That's why @danielmarbach and I decided to throw if multiple mapped properties were detected for Raven.

If we agree that is good, proper, and correct, then this issue should be closed?

**Comment by andreasohlund** [comment]
Fixed on develop, will go out in 4.0.0
